apiVersion: v1
kind: Service
metadata:
  namespace: interplan-prod
  name: node-page-service
spec:
  type: NodePort
  selector:
    app: interplan-pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
      name: "app-access"
    # - protocol: TCP
    #   port: 3001
    #   targetPort: 3001
    #   nodePort: 31001
    #   name: "build-access"