apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: interplan-prod
  name: app-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: "interplan-prod-pv"