apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: interplan-prod
  name: neo4j-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: "neo4j-prod-pv"