apiVersion: v1
kind: Service
metadata:
  namespace: interplan-prod
  name: neo4j-db-service
spec:
  type: NodePort
  selector:
    app: interplan-pod
  ports:
    - protocol: TCP
      port: 7474
      targetPort: 7474
      nodePort: 31474
      name: "neo4j-http"

    - protocol: TCP
      port: 7473
      targetPort: 7473
      nodePort: 31473
      name: "neo4j-https"

    - protocol: TCP
      port: 7687
      targetPort: 7687
      nodePort: 31687
      name: "neo4j-bolt"
